### ISSUE TITLE
Unable to remove option already added

### ISSUE THREAD

**Issue by Eaglw** [natankeddem/autopve#1]
I'm trying to edit the "default" profile, and I can't remove the "zfs.raid" parameter in the "disk" tab. I want to use ext4, so it results in a conflict. 
I've noticed that in general any value added once cannot be removed. I've tried to edit the json file, but even that is useless.
I'm using docker. 

Anyway, that's a great project man!

**Comment by natankeddem** [comment]
Thank you for bringing this to my attention @Eaglw. I believe I have fixed the issue. Please let me know if you are still experiencing this issue after updating to https://github.com/natankeddem/autopve/releases/tag/v1.0.1.

**Comment by Eaglw** [comment]
It's working. Thanks for the fast fix!
