### ISSUE TITLE
Can't see any filters

### ISSUE THREAD

**Issue by GusevVictor** [natankeddem/autopve#11]
Dear all, please help me.

docker:latest. I don't understand how to use that. The list is empty:

![image](https://github.com/user-attachments/assets/ce879027-3047-4b3a-b339-7e04a87bdffb)

**Comment by GusevVictor** [comment]
After first request I can chouse some of keys but no filter.

It's so strange. How can I enter a mac address, for example without connect and install Default?

![image](https://github.com/user-attachments/assets/68e1979a-4806-49fc-b538-5ab70d3f6657)

**Comment by GusevVictor** [comment]
Do I need generate fake request for each host before real install?

**Comment by GusevVictor** [comment]
Oh... It seems that I realized how to achive that. After put my own key value there is need to TAB key for save it. So strange but ok. Thanks for software! It's awesome!

**Comment by natankeddem** [comment]
Hello @GusevVictor,
The filters get auto populated as selections as you get requests in, there is no way for the software to guess what kind of client hardware you have. If you already know what you are looking to filter against you can manually type your filter in the selection field:
[autopvefilter0.webm](https://github.com/user-attachments/assets/edd8245f-7bdb-469a-a212-2642f3102b8b)

**Comment by GusevVictor** [comment]
You're brilliant! Thank a lot!
