### ISSUE TITLE
Change color current answers file [Enhancement] 

### ISSUE THREAD

**Issue by GusevVictor** [natankeddem/autopve#12]
Hi!

Could you change color the current working file? It's little bit hard to remember which is current file when work.

![image](https://github.com/user-attachments/assets/2039fc6c-ebb3-49b2-a56d-814b18198713)

Best regards!

**Comment by natankeddem** [comment]
Hello @GusevVictor,
While I could come up with some way to style the currently active answer for better visibility, I think the header is adequate at conveying the active answer?
![image](https://github.com/user-attachments/assets/d8ddecea-c35c-402b-94be-df14ea336e07)
