### ISSUE TITLE
disk_list and filter under [disk-setup]

### ISSUE THREAD

**Issue by sushifor1** [natankeddem/autopve#3]
These two properties under [disk-setup] are supposed to be mutually exclusive:

> disk_list -- List of disks to use. Useful if you are sure about the disk names. For example: disk_list = ["sda", "sdb"]
> filter -- Filter against UDEV properties to select the disks for the installation. See [filters]>(https://pve.proxmox.com/wiki/Automated_Installation#Filters).
>NOTE: Use either disk_list or filter. Defining both is not allowed.

When I have disk_list defined under "Default" and a filter (eg. filter.ID_SERIAL) defined in a specific profile, both properties end up being included in the answer file. 

I took a quick look at the code and I believe there is no validation logic for the time being. This is easy to work around, but some guardrails probably would be a welcome addition as I can see this becoming a popular tool in the future :)

Thank you for making this btw.

**Comment by natankeddem** [comment]
@sushifor1 thank you for bringing this up, I understand your concern. I will try to have some improvements in this area soon.

**Comment by natankeddem** [comment]
I have released v1.0.2 with some improvements regarding your issue. I added some input sanitization with notifications. I also added some logic which drives the flattening of answers to allow the non-default filter/disk-list to remove the overridden key entry so both would not be given.

**Comment by sushifor1** [comment]
Thank you for such a quick update. I've tested v1.0.2 and confirmed the disk_list & filter validation works.
