### ISSUE TITLE
Network filter bug

### ISSUE THREAD

**Issue by djtobyy** [natankeddem/autopve#4]
Hi,

The actual filters for the network use an other definition (perhaps new?):
filter.ID_NET_NAME_MAC = "*MACADDRESS"

In autopve it would be a wrong definition:
filter = "ID_NET_NAME_MAC = "*MACADDRESS""

Therefore there is no possibility to filter any interface.

https://pve.proxmox.com/wiki/Automated_Installation#Filters
Would be nice to have a fix!

Best,
Tobi

**Comment by djtobyy** [comment]
Only when using the network setting from the answer file.

**Comment by natankeddem** [comment]
Hi @djtobyy,
Thank you for this report. Is utilizing arbitrary keys not working correctly for you? It looks correct on my end but maybe I am not understanding your issue correctly? There is an example of setting a filter on the video demonstration.
![image](https://github.com/natankeddem/autopve/assets/44515217/0a2d8f16-3b14-41d3-aead-21e172d6dc38)

**Comment by natankeddem** [comment]
Hi @djtobyy,
Did my comment solve your issue or do you still believe there is a problem?

**Comment by djtobyy** [comment]
Hi, it‘s just a bit confusing.You can select „filter“ from the dropdown and I thought I can insert the mac filter there.Am 20.06.2024 um 03:32 schrieb Natan Keddem ***@***.***>:﻿
Hi @djtobyy,
Did my comment solve your issue or do you still believe there is a problem?

**Comment by natankeddem** [comment]
Hi @djtobyy,
I will close this issue for now then since it seems like you got it working. I will think about how to make it less confusing. Perhaps I might change the help tooltip to be more verbose. Thank you for your feedback.
