### ISSUE TITLE
The work of the /answer link

### ISSUE THREAD

**Issue by Apatch43u** [natankeddem/autopve#7]
Hi!
How to use the answer link correctly, when going to /answer it gives an error
Undocumented
Error: Internal Server Error

Get Request return:
{
    "detail": "Method Not Allowed"
}

Thanks for the answer!
![1](https://github.com/user-attachments/assets/25ab30f2-9a0e-4fd8-8c4d-5480e5664442)
![image](https://github.com/user-attachments/assets/4ebd5d3f-cbc0-4fb5-87d4-81cab4270aa1)

**Comment by natankeddem** [comment]
Hi @Apatch43u,
How are you hosting autopve, docker or in an lxc container?

**Comment by Apatch43u** [comment]
I use lxc container debian 12 on proxmox 8.2

**Comment by natankeddem** [comment]
Did you use the ansible playbook to install?

**Comment by Apatch43u** [comment]
Right.

**Comment by Apatch43u** [comment]
version 2.14.16

**Comment by natankeddem** [comment]
Why are you trying to utilize a GET? Is there a use case I am missing? The standard Proxmox installer utilizes a POST.

**Comment by natankeddem** [comment]
This is the python script I am utilizing to simulate the Proxmox installer for reference.
```py
import requests
import json

p = """
{
  "product": {
    "fullname": "Proxmox VE",
    "product": "pve",
    "enable_btrfs": true
  },
  "iso": {
    "release": "8.2",
    "isorelease": "1"
  },
  "dmi": {
    "system": {
      "serial": "",
      "name": "Standard PC (i440FX + PIIX, 1996)",
      "sku": "",
      "uuid": "eecb0a97-633b-4c83-8554-ae877f77cbb3"
    },
    "baseboard": {},
    "chassis": {
      "serial": "",
      "asset_tag": ""
    }
  },
  "network_interfaces": [
    {
      "link": "ens18",
      "mac": "bc:24:11:08:a4:ea"
    }
  ]
}
"""
r = requests.post(url="http://10.1.7.66:8080/answer", json=json.loads(p))
print(r.content)
```

**Comment by Apatch43u** [comment]
Everything works! My mistake was that I tried to test the link with the tools available besides proxmox ve itself, without using the request body, thanks for your time, have a good day)

**Comment by natankeddem** [comment]
I am happy everything is working for you.
